### PR TITLE
Fixed the banner from getting the clicks.

### LINKED ISSUE #77: Make the banner unclickable
The is clickable but I want it to be unclickable without the hover cursor and the highlight when hovered over.

### PR DESCRIPTION
**Pull request by praveenscience**
Fixed the header image from getting clicks by checking the class name and returning `false` if it has the class `header-img`.

Fixes #77.

### CODE REVIEW

**Comment by praveenscience** [comment]
Fixes Issue #77.

**Review by adlyloukil — CHANGES_REQUESTED** [review]
There is still a cursor issue, therefore you can still interact with the banner. Please remove the cursor and highlight

**Comment by praveenscience** [comment]
Okay will do. 👍

**Comment by praveenscience** [comment]
@adlyloukil FIxed.. 👍

**Comment by praveenscience** [comment]
@adlyloukil Can you check this? This is fixed now... 😄

**Comment by adlyloukil** [comment]
@praveenscience Thanks

**Comment by praveenscience** [comment]
You are welcome... 👍

**Pull request closed without merging**
